name: Bursary-Management-Application
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: Start-Process powershell -Verb RunAs
      - run: Invoke-WebRequest -Uri https://aka.ms/install-winget -OutFile winget-installer.msi
      - run: Start-Process msiexec.exe -Wait -ArgumentList '/I winget-installer.msi'
      - run: Remove-Item -Path winget-installer.msi
      - run: winget -v
      - run: winget install Microsoft.SQLServer.2022.Express
