name: Bursary-Management-Application
run-name: ${{ github.actor }} deploying database
on:
  push:
    branches:
      - main
      - development_stable
      - workflows_pipeline
    paths:
      - "**.sql"
      - "**.yml"
jobs:
  create-database:
    name: Create Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/sql-action@v2.2.1
        with:        
          connection-string: ${{ secrets.BURSARY_MANAGEMENT_APPLICATION_DB }}
          path: './createDatabase.sql'
          action: 'publish'

  create-tables:
    name: Create Tables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/sql-action@v2.2.1
        with:        
          connection-string: ${{ secrets.BURSARY_MANAGEMENT_APPLICATION_DB }}
          path: './createTablesScript.sql'
          action: 'publish'

  create-procedure:
    name: Create Stored Procedure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/sql-action@v2.2.1
        with:        
          connection-string: ${{ secrets.BURSARY_MANAGEMENT_APPLICATION_DB }}
          path: './StoredProcedure.sql'
          action: 'publish'
